CREATE TABLE STUDENTS (
  ID BIGINT(30) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(40) DEFAULT '',
  LAST_NAME VARCHAR(50) DEFAULT '',
  BIRTH_DATE DATE DEFAULT '2015-03-19',
  RECORD_BOOK_NUMBER BIGINT(30) DEFAULT 0,
  EXPELLED BOOLEAN DEFAULT FALSE,
  GROUP_ID BIGINT(30) DEFAULT 0
);

CREATE TABLE GROUPS (
  ID BIGINT(30) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  GROUP_NAME VARCHAR(30) DEFAULT '',
  GROUP_TEACHER BIGINT(30) DEFAULT 0
);

CREATE TABLE TEACHERS (
  ID BIGINT(30) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EMAIL VARCHAR(40) DEFAULT '',
  PASSWORD VARCHAR(40) DEFAULT '',
  FIRST_NAME VARCHAR(40) DEFAULT '',
  LAST_NAME VARCHAR(40) DEFAULT '',
  TEACHER_POSITION VARCHAR(40) DEFAULT '',
  SUPERVISING_GROUP_ID BIGINT(30) DEFAULT 0
);

CREATE TABLE LESSONS (
  ID BIGINT(30) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  LESSON_NAME VARCHAR(30) DEFAULT ''
);

CREATE TABLE ATTENDANCE (
  ID BIGINT(30) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  STUDENT_ID BIGINT(30) NOT NULL,
  LESSON_ID BIGINT(30) NOT NULL,
  ATTENDANCE_DATE DATE NOT NULL,
  MARK INT(4) DEFAULT 2
);


INSERT INTO TEACHERS(EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, TEACHER_POSITION) VALUES
('teacher@test.com', '12345', 'Oleh', 'Kudryavcev', 'Superviser');

INSERT INTO STUDENTS(FIRST_NAME, LAST_NAME, RECORD_BOOK_NUMBER) VALUES ('OLEH', 'MAX', 1);

ALTER TABLE STUDENTS ADD COLUMN EXPELLED BOOLEAN DEFAULT FALSE;

ALTER TABLE ATTENDANCE ADD COLUMN PRESENCE BOOLEAN DEFAULT FALSE;